### PR TITLE
Loosen prosemirror-tables dependency

### PR DESCRIPTION
**Pull request by DouweM**
I wasn't able to use `tiptap` because `yarn check` was outputting this error:

```
error "tiptap-utils#prosemirror-utils#prosemirror-tables@^0.6.5" doesn't satisfy found match of "prosemirror-tables@0.7.7"
```

The underlying reason is that `tiptap@0.17.0` depends on `tiptap-utils@^0.3.0`, which depends on `prosemirror-tables ^0.7.7`, _and_ on `prosemirror-utils ^0.6.6`, which (as seen below) currently depends on `prosemirror-tables ^0.6.5`. These `prosemirror-tables` dependencies are incompatible.

### CODE REVIEW

**Comment by eshvedai** [comment]
why don't we just bump `prosemirror-tables` to the latest version here?

**Comment by DouweM** [comment]
@eshvedai I didn't want to make the requirement tighter than it needs to be, because evidently prosemirror-utils works fine with prosemirror-tables 0.6.5 today, but I'm happy to make the change if you'd prefer that.

**Comment by eshvedai** [comment]
yeah I'd prefer bumping pm-tables to the latest version

**Comment by DouweM** [comment]
@eshvedai Updated!

**Pull request merged**
